"""
PEPC PDF Katalog Keşif Sistemi - Anahtar Kelimeler ve Markalar
"""
from typing import List, Optional

# Marka alias'ları - Arama genişletme için
BRAND_ALIASES = {
    "caterpillar": ["caterpillar", "cat"],
    "volvo": ["volvo", "volvo ce", "volvo construction equipment"],
    "komatsu": ["komatsu", "komatsu ltd"],
    "hitachi": ["hitachi", "hitachi construction", "hitachi zaxis"],
    "jcb": ["jcb"],
    "doosan": ["doosan", "daewoo doosan", "daewoo"],
    "hyundai": ["hyundai", "hyundai construction", "hyundai robex"],
    "liebherr": ["liebherr"],
    "kobelco": ["kobelco", "kobelco sk"],
    "case": ["case", "case ih", "case construction"],
    "john deere": ["john deere", "deere", "jd"],
    "new holland": ["new holland", "nh", "newholland"],
    "bobcat": ["bobcat"],
    "takeuchi": ["takeuchi"],
    "kubota": ["kubota"],
    "yanmar": ["yanmar"],
    "hidromek": ["hidromek", "hmk"],
    "xcmg": ["xcmg"],
    "sany": ["sany"],
    "zoomlion": ["zoomlion"],
    "shantui": ["shantui"],
    "lonking": ["lonking"],
    "liugong": ["liugong"],
    "dynapac": ["dynapac"],
    "bomag": ["bomag"],
    "hamm": ["hamm"],
    "wirtgen": ["wirtgen"],
    "vogele": ["vogele", "vögele"],
    "ammann": ["ammann"],
    "terex": ["terex"],
    "tadano": ["tadano"],
    "grove": ["grove"],
    "manitou": ["manitou"],
    "merlo": ["merlo"],
    "toyota": ["toyota", "toyota forklift"],
    "linde": ["linde", "linde forklift"],
    "hyster": ["hyster"],
    "yale": ["yale", "yale forklift"],
    "mitsubishi": ["mitsubishi", "mitsubishi forklift"],
    "still": ["still"],
    "jungheinrich": ["jungheinrich"],
    "clark": ["clark", "clark forklift"],
    "crown": ["crown", "crown forklift"],
    "tcm": ["tcm", "tcm forklift"],
    "cummins": ["cummins"],
    "perkins": ["perkins"],
    "deutz": ["deutz"],
    "isuzu": ["isuzu"]
}


def expand_brand_queries(brand: str, model: Optional[str], keyword: str) -> List[str]:
    """
    Marka alias'ları ile sorgu listesi oluştur
    
    Args:
        brand: Marka adı (örn: "caterpillar")
        model: Model numarası (örn: "320D", None olabilir)
        keyword: Arama anahtar kelimesi (örn: "parts catalog")
    
    Returns:
        Genişletilmiş sorgu listesi
    
    Örnek:
        expand_brand_queries("caterpillar", "320D", "parts catalog")
        → [
            '"caterpillar" "320D" parts catalog',
            '"cat" "320D" parts catalog'
          ]
    """
    aliases = BRAND_ALIASES.get(brand.lower(), [brand])
    queries = []
    
    for alias in aliases:
        if model:
            # Marka + Model + Keyword
            queries.append(f'"{alias}" "{model}" {keyword}')
        else:
            # Sadece Marka + Keyword
            queries.append(f'"{alias}" {keyword}')
    
    return queries


def get_brand_aliases(brand: str) -> List[str]:
    """Bir markanın tüm alias'larını döndür"""
    return BRAND_ALIASES.get(brand.lower(), [brand])


DOCUMENT_KEYWORDS = {
    "parts_catalog": {
        "en": ["parts catalog", "parts catalogue"],
        "de": ["teilekatalog", "ersatzteilkatalog"],
        "fr": ["catalogue de pièces", "catalogue pièces détachées"],
        "es": ["catálogo de piezas", "catálogo de partes"],
        "it": ["catalogo ricambi", "catalogo parti"],
        "pt": ["catálogo de peças", "catálogo de componentes"],
        "ru": ["каталог запчастей", "каталог деталей"],
        "tr": ["parça kataloğu", "yedek parça kataloğu"],
        "zh": ["零件目录", "配件目录"],
        "ja": ["部品カタログ", "パーツカタログ"],
        "ko": ["부품 카탈로그", "파츠 카talog"],
        "ar": ["كتالوج قطع الغيار"],
        "pl": ["katalog części", "katalog części zamiennych"],
        "nl": ["onderdelen catalogus", "onderdelencatalogus"],
        "sv": ["reservdelskatalog", "delkatalog"]
    },
    "parts_book": {
        "en": ["parts book", "illustrated parts book"],
        "de": ["teilebuch", "ersatzteilbuch", "stückliste"],
        "fr": ["livre de pièces", "manuel illustré des pièces"],
        "es": ["libro de piezas", "libro de partes"],
        "it": ["libro ricambi", "libro delle parti"],
        "pt": ["livro de peças", "manual de peças ilustrado"],
        "ru": ["книга запчастей", "иллюстрированный каталог"],
        "tr": ["parça kitabı", "yedek parça kitabı"],
        "zh": ["零件手册", "配件手册"],
        "ja": ["パーツブック", "部品集"],
        "ko": ["부품집", "파츠북"],
        "ar": ["كتاب قطع الغيار"],
        "pl": ["książka części", "ilustrowany katalog"],
        "nl": ["onderdelenboek", "partsboek"],
        "sv": ["reservdelsbok", "delbok"]
    },
    "parts_manual": {
        "en": ["parts manual", "illustrated parts manual", "IPL"],
        "de": ["teilehandbuch", "ersatzteilhandbuch"],
        "fr": ["manuel des pièces", "manuel pièces détachées"],
        "es": ["manual de piezas", "manual de partes"],
        "it": ["manuale ricambi", "manuale parti"],
        "pt": ["manual de peças", "manual de componentes"],
        "ru": ["руководство по запчастям", "справочник запчастей"],
        "tr": ["parça el kitabı", "yedek parça kılavuzu"],
        "zh": ["零件手册", "部件手册"],
        "ja": ["パーツマニュアル", "部品マニュアル"],
        "ko": ["부품 매뉴얼", "파츠 매뉴얼"],
        "ar": ["دليل قطع الغيار"],
        "pl": ["instrukcja części", "podręcznik części"],
        "nl": ["onderdelen handleiding"],
        "sv": ["reservdelsmanual", "delmanual"]
    },
    "parts_list": {
        "en": ["parts list", "spare parts list", "BOM", "bill of materials"],
        "de": ["teileliste", "ersatzteilliste", "stückliste"],
        "fr": ["liste des pièces", "nomenclature"],
        "es": ["lista de piezas", "lista de repuestos"],
        "it": ["lista ricambi", "elenco parti", "distinta base"],
        "pt": ["lista de peças", "relação de peças"],
        "ru": ["список запчастей", "перечень деталей"],
        "tr": ["parça listesi", "yedek parça listesi"],
        "zh": ["零件清单", "配件清单", "物料清单"],
        "ja": ["部品リスト", "パーツリスト"],
        "ko": ["부품 목록", "파츠 리스트"],
        "ar": ["قائمة قطع الغيار"],
        "pl": ["lista części", "wykaz części"],
        "nl": ["onderdelenlijst", "stuklijst"],
        "sv": ["reservdelslista", "dellista"]
    },
    "repair_manual": {
        "en": ["repair manual", "overhaul manual", "rebuild manual"],
        "de": ["reparaturanleitung", "reparaturhandbuch", "instandsetzungsanleitung"],
        "fr": ["manuel de réparation", "guide de réparation"],
        "es": ["manual de reparación", "guía de reparación"],
        "it": ["manuale di riparazione", "guida alla riparazione"],
        "pt": ["manual de reparo", "manual de reparação"],
        "ru": ["руководство по ремонту", "инструкция по ремонту"],
        "tr": ["tamir kılavuzu", "onarım el kitabı", "revizyon kılavuzu"],
        "zh": ["维修手册", "修理手册", "大修手册"],
        "ja": ["修理マニュアル", "整備マニュアル"],
        "ko": ["수리 매뉴얼", "정비 매뉴얼"],
        "ar": ["دليل الإصلاح"],
        "pl": ["instrukcja naprawy", "podręcznik naprawy"],
        "nl": ["reparatiehandleiding"],
        "sv": ["reparationshandbok"]
    },
    "workshop_manual": {
        "en": ["workshop manual", "factory service manual", "WSM", "FSM"],
        "de": ["werkstatthandbuch", "WHB"],
        "fr": ["manuel d'atelier", "manuel de service"],
        "es": ["manual de taller", "manual de servicio"],
        "it": ["manuale d'officina", "manuale di servizio"],
        "pt": ["manual de oficina", "manual de serviço"],
        "ru": ["руководство по техобслуживанию", "мануал"],
        "tr": ["atölye el kitabı", "servis kılavuzu"],
        "zh": ["维修车间手册", "工厂服务手册"],
        "ja": ["整備解説書", "サービスマニュアル"],
        "ko": ["워크샵 매뉴얼", "공장 서비스 매뉴얼"],
        "ar": ["دليل ورشة العمل"],
        "pl": ["instrukcja warsztatowa"],
        "nl": ["werkplaatshandboek"],
        "sv": ["verkstadshandbok"]
    },
    "shop_manual": {
        "en": ["shop manual", "service manual", "technical manual"],
        "de": ["servicehandbuch", "technisches handbuch"],
        "fr": ["manuel de service", "manuel technique"],
        "es": ["manual de servicio", "manual técnico"],
        "it": ["manuale di servizio", "manuale tecnico"],
        "pt": ["manual de serviço", "manual técnico"],
        "ru": ["сервисный мануал", "техническое руководство"],
        "tr": ["servis el kitabı", "teknik kılavuz"],
        "zh": ["服务手册", "技术手册"],
        "ja": ["サービスマニュアル", "技術マニュアル"],
        "ko": ["서비스 매뉴얼", "기술 매뉴얼"],
        "ar": ["دليل الخدمة"],
        "pl": ["instrukcja serwisowa"],
        "nl": ["servicehandleiding"],
        "sv": ["servicehandbok"]
    },
    "operator_manual": {
        "en": ["operator manual", "owner's manual", "user manual", "OMM"],
        "de": ["betriebsanleitung", "bedienungsanleitung"],
        "fr": ["manuel de l'opérateur", "manuel d'utilisation"],
        "es": ["manual del operador", "manual de usuario"],
        "it": ["manuale operatore", "manuale d'uso"],
        "pt": ["manual do operador", "manual do usuário"],
        "ru": ["руководство оператора", "инструкция по эксплуатации"],
        "tr": ["operatör el kitabı", "kullanım kılavuzu"],
        "zh": ["操作手册", "用户手册"],
        "ja": ["取扱説明書", "操作マニュアル"],
        "ko": ["운전자 매뉴얼", "사용자 설명서"],
        "ar": ["دليل المشغل"],
        "pl": ["instrukcja obsługi"],
        "nl": ["gebruikershandleiding"],
        "sv": ["bruksanvisning"]
    },
    "wiring_diagram": {
        "en": ["wiring diagram", "electrical schematic", "circuit diagram"],
        "de": ["schaltplan", "stromlaufplan", "elektroschaltplan"],
        "fr": ["schéma électrique", "schéma de câblage"],
        "es": ["diagrama eléctrico", "esquema eléctrico"],
        "it": ["schema elettrico", "diagramma elettrico"],
        "pt": ["diagrama elétrico", "esquema elétrico"],
        "ru": ["электросхема", "схема проводки"],
        "tr": ["elektrik şeması", "kablo şeması"],
        "zh": ["电路图", "接线图"],
        "ja": ["配線図", "電気回路図"],
        "ko": ["배선도", "전기 회로도"],
        "ar": ["مخطط الأسلاك"],
        "pl": ["schemat elektryczny"],
        "nl": ["bedradingsschema"],
        "sv": ["kopplingsschema"]
    },
    "hydraulic_diagram": {
        "en": ["hydraulic diagram", "hydraulic schematic"],
        "de": ["hydraulikschema", "hydraulikplan"],
        "fr": ["schéma hydraulique"],
        "es": ["diagrama hidráulico", "esquema hidráulico"],
        "it": ["schema idraulico"],
        "pt": ["diagrama hidráulico"],
        "ru": ["гидросхема", "гидравлическая схема"],
        "tr": ["hidrolik şema", "hidrolik devre"],
        "zh": ["液压图", "液压原理图"],
        "ja": ["油圧回路図"],
        "ko": ["유압 회로도"],
        "ar": ["مخطط هيدروليكي"],
        "pl": ["schemat hydrauliczny"],
        "nl": ["hydraulisch schema"],
        "sv": ["hydraulschema"]
    },
    "troubleshooting": {
        "en": ["troubleshooting", "fault codes", "error codes", "DTC"],
        "de": ["fehlersuche", "fehlercodes", "diagnose"],
        "fr": ["dépannage", "codes défaut", "diagnostic"],
        "es": ["solución de problemas", "códigos de falla"],
        "it": ["risoluzione problemi", "codici errore"],
        "pt": ["solução de problemas", "códigos de falha"],
        "ru": ["поиск неисправностей", "коды ошибок"],
        "tr": ["arıza giderme", "hata kodları", "arıza teşhis"],
        "zh": ["故障排除", "故障代码"],
        "ja": ["トラブルシューティング", "エラーコード"],
        "ko": ["문제 해결", "고장 코드"],
        "ar": ["استكشاف الأخطاء"],
        "pl": ["rozwiązywanie problemów", "kody błędów"],
        "nl": ["probleemoplossing", "foutcodes"],
        "sv": ["felsökning", "felkoder"]
    }
}

EQUIPMENT_KEYWORDS = {
    "excavator": {
        "en": ["excavator", "digger", "backhoe"],
        "de": ["bagger", "hydraulikbagger", "raupenbagger"],
        "fr": ["excavatrice", "pelleteuse", "pelle hydraulique"],
        "es": ["excavadora", "retroexcavadora"],
        "it": ["escavatore", "escavatrice"],
        "pt": ["escavadeira", "retroescavadeira"],
        "ru": ["экскаватор", "гусеничный экскаватор"],
        "tr": ["ekskavatör", "kazıcı"],
        "zh": ["挖掘机", "挖机"],
        "ja": ["ショベル", "油圧ショベル"],
        "ko": ["굴삭기", "포크레인"],
        "ar": ["حفارة"],
        "pl": ["koparka"],
        "nl": ["graafmachine"],
        "sv": ["grävmaskin"]
    },
    "loader": {
        "en": ["wheel loader", "front loader", "loader"],
        "de": ["radlader", "frontlader", "lader"],
        "fr": ["chargeuse", "chargeur frontal"],
        "es": ["cargadora", "pala cargadora"],
        "it": ["pala gommata", "caricatore"],
        "pt": ["carregadeira", "pá carregadeira"],
        "ru": ["погрузчик", "фронтальный погрузчик"],
        "tr": ["yükleyici", "loder"],
        "zh": ["装载机", "铲车"],
        "ja": ["ホイールローダー"],
        "ko": ["로더", "휠로더"],
        "ar": ["لودر"],
        "pl": ["ładowarka"],
        "nl": ["wiellader"],
        "sv": ["hjullastare"]
    },
    "dozer": {
        "en": ["bulldozer", "dozer", "crawler dozer"],
        "de": ["planierraupe", "bulldozer", "raupe"],
        "fr": ["bulldozer", "bouteur"],
        "es": ["bulldozer", "topadora"],
        "it": ["bulldozer", "apripista"],
        "pt": ["trator de esteira", "bulldozer"],
        "ru": ["бульдозер"],
        "tr": ["dozer", "buldozer"],
        "zh": ["推土机"],
        "ja": ["ブルドーザー"],
        "ko": ["불도저"],
        "ar": ["بلدوزر"],
        "pl": ["spycharka"],
        "nl": ["bulldozer"],
        "sv": ["bulldozer"]
    },
    "engine": {
        "en": ["engine", "diesel engine", "motor"],
        "de": ["motor", "dieselmotor"],
        "fr": ["moteur", "moteur diesel"],
        "es": ["motor", "motor diesel"],
        "it": ["motore", "motore diesel"],
        "pt": ["motor", "motor diesel"],
        "ru": ["двигатель", "дизель"],
        "tr": ["motor", "dizel motor"],
        "zh": ["发动机", "柴油机"],
        "ja": ["エンジン"],
        "ko": ["엔진"],
        "ar": ["محرك"],
        "pl": ["silnik"],
        "nl": ["motor"],
        "sv": ["motor"]
    },
    "forklift": {
        "en": ["forklift", "lift truck", "fork truck"],
        "de": ["gabelstapler", "stapler"],
        "fr": ["chariot élévateur"],
        "es": ["montacargas", "carretilla elevadora"],
        "it": ["carrello elevatore", "muletto"],
        "pt": ["empilhadeira"],
        "ru": ["вилочный погрузчик", "автопогрузчик"],
        "tr": ["forklift"],
        "zh": ["叉车"],
        "ja": ["フォークリフト"],
        "ko": ["지ge차"],
        "ar": ["رافعة شوكية"],
        "pl": ["wózek widłowy"],
        "nl": ["vorkheftruck"],
        "sv": ["gaffeltruck"]
    },
    "crane": {
        "en": ["crane", "mobile crane", "crawler crane"],
        "de": ["kran", "mobilkran"],
        "fr": ["grue", "grue mobile"],
        "es": ["grúa", "grúa móvil"],
        "it": ["gru", "gru mobile"],
        "pt": ["guindaste", "grua"],
        "ru": ["кран", "автокран"],
        "tr": ["vinç", "mobil vinç"],
        "zh": ["起重机", "吊车"],
        "ja": ["クレーン"],
        "ko": ["크레인"],
        "ar": ["رافعة"],
        "pl": ["żuraw", "dźwig"],
        "nl": ["kraan"],
        "sv": ["kran"]
    },
    "generator": {
        "en": ["generator", "genset", "diesel generator"],
        "de": ["generator", "stromerzeuger"],
        "fr": ["groupe électrogène", "générateur"],
        "es": ["generador", "grupo electrógeno"],
        "it": ["generatore", "gruppo elettrogeno"],
        "pt": ["gerador", "grupo gerador"],
        "ru": ["генератор", "дизель-генератор"],
        "tr": ["jeneratör"],
        "zh": ["发电机"],
        "ja": ["発電機"],
        "ko": ["발전기"],
        "ar": ["مولد"],
        "pl": ["generator"],
        "nl": ["generator"],
        "sv": ["generator"]
    },
    "compressor": {
        "en": ["compressor", "air compressor"],
        "de": ["kompressor", "luftkompressor"],
        "fr": ["compresseur"],
        "es": ["compresor"],
        "it": ["compressore"],
        "pt": ["compressor"],
        "ru": ["компрессор"],
        "tr": ["kompresör"],
        "zh": ["压缩机", "空压机"],
        "ja": ["コンプレッサー"],
        "ko": ["컴프레서"],
        "ar": ["ضاغط"],
        "pl": ["kompresor"],
        "nl": ["compressor"],
        "sv": ["kompressor"]
    },
    "grader": {
        "en": ["motor grader", "grader", "road grader"],
        "de": ["motorgrader", "grader"],
        "fr": ["niveleuse", "grader"],
        "es": ["motoniveladora", "niveladora"],
        "it": ["livellatrice", "grader"],
        "pt": ["motoniveladora"],
        "ru": ["автогрейдер", "грейдер"],
        "tr": ["greyder"],
        "zh": ["平地机"],
        "ja": ["モーターグレーダー"],
        "ko": ["모터그레이더"],
        "ar": ["ممهدة"],
        "pl": ["równiarka"],
        "nl": ["grader"],
        "sv": ["väghyvel"]
    },
    "dump_truck": {
        "en": ["dump truck", "articulated dump truck", "haul truck"],
        "de": ["muldenkipper", "dumper"],
        "fr": ["tombereau", "dumper"],
        "es": ["camión volquete", "dumper"],
        "it": ["dumper"],
        "pt": ["caminhão basculante"],
        "ru": ["самосвал", "думпер"],
        "tr": ["damperli kamyon", "kaya kamyonu"],
        "zh": ["自卸车", "矿用卡车"],
        "ja": ["ダンプトラック"],
        "ko": ["덤프트럭"],
        "ar": ["شاحنة قلابة"],
        "pl": ["wozidło"],
        "nl": ["dumper"],
        "sv": ["dumper"]
    },
    "roller": {
        "en": ["roller", "road roller", "compactor", "vibratory roller"],
        "de": ["walze", "straßenwalze", "vibrationswalze"],
        "fr": ["rouleau", "compacteur"],
        "es": ["rodillo", "compactador"],
        "it": ["rullo compattatore"],
        "pt": ["rolo compactador"],
        "ru": ["каток", "виброкаток"],
        "tr": ["silindir", "kompaktör"],
        "zh": ["压路机"],
        "ja": ["ロードローラー"],
        "ko": ["로드롤러"],
        "ar": ["رصاصة"],
        "pl": ["walec"],
        "nl": ["wals"],
        "sv": ["vält"]
    },
    "telehandler": {
        "en": ["telehandler", "telescopic handler"],
        "de": ["teleskoplader"],
        "fr": ["chariot télescopique"],
        "es": ["manipulador telescópico"],
        "it": ["sollevatore telescobico"],
        "pt": ["manipulador telescópico"],
        "ru": ["телескопический погрузчик"],
        "tr": ["teleskopik yükleyici"],
        "zh": ["伸缩臂叉装车"],
        "ja": ["テレハンドラー"],
        "ko": ["텔레핸들러"],
        "ar": ["رافعة تلسكوبية"],
        "pl": ["ładowarka teleskopowa"],
        "nl": ["verreiker"],
        "sv": ["teleskoplastare"]
    },
    "skid_steer": {
        "en": ["skid steer", "skid steer loader", "bobcat"],
        "de": ["kompaktlader"],
        "fr": ["chargeuse compacte", "mini-chargeuse"],
        "es": ["minicargadora"],
        "it": ["minipala"],
        "pt": ["mini carregadeira"],
        "ru": ["мини-погрузчик"],
        "tr": ["mini yükleyici"],
        "zh": ["滑移装载机"],
        "ja": ["スキッドステアローダー"],
        "ko": ["스키드스티어로더"],
        "ar": ["لودر صغير"],
        "pl": ["ładowarka kompaktowa"],
        "nl": ["compactlader"],
        "sv": ["kompaktlastare"]
    }
}

# Marka listesi - Frontend dropdown için
BRAND_LIST = [
    "caterpillar",
    "komatsu",
    "volvo",
    "hitachi",
    "jcb",
    "hyundai",
    "doosan",
    "kobelco",
    "case",
    "liebherr",
    "new holland",
    "john deere",
    "hidromek",
    "bobcat",
    "kubota",
    "takeuchi",
    "yanmar",
    "xcmg",
    "sany",
    "zoomlion",
    "shantui",
    "lonking",
    "liugong",
    "dynapac",
    "bomag",
    "hamm",
    "wirtgen",
    "vogele",
    "ammann",
    "terex",
    "tadano",
    "grove",
    "manitou",
    "merlo",
    "toyota",
    "linde",
    "hyster",
    "yale",
    "mitsubishi",
    "still",
    "jungheinrich",
    "clark",
    "crown",
    "tcm"
]

# Marka varyasyonları (arama eşleştirme için)
BRANDS = {
    "caterpillar": ["CAT", "Caterpillar", "CATERPILLAR"],
    "komatsu": ["Komatsu", "KOMATSU", "小松"],
    "hitachi": ["Hitachi", "HITACHI", "日立"],
    "volvo": ["Volvo", "VOLVO", "Volvo CE"],
    "jcb": ["JCB"],
    "liebherr": ["Liebherr", "LIEBHERR"],
    "doosan": ["Doosan", "DOOSAN", "Daewoo"],
    "hyundai": ["Hyundai", "HYUNDAI", "현대"],
    "kobelco": ["Kobelco", "KOBELCO"],
    "case": ["CASE", "Case"],
    "john deere": ["John Deere", "JD", "Deere"],
    "kubota": ["Kubota", "KUBOTA"],
    "yanmar": ["Yanmar", "YANMAR"],
    "cummins": ["Cummins", "CUMMINS"],
    "perkins": ["Perkins", "PERKINS"],
    "deutz": ["Deutz", "DEUTZ"],
    "isuzu": ["Isuzu", "ISUZU"],
    "mitsubishi": ["Mitsubishi", "MITSUBISHI"],
    "takeuchi": ["Takeuchi", "TAKEUCHI"],
    "bobcat": ["Bobcat", "BOBCAT"],
    "new holland": ["New Holland", "NH"],
    "terex": ["Terex", "TEREX"],
    "jlg": ["JLG"],
    "genie": ["Genie", "GENIE"],
    "manitou": ["Manitou", "MANITOU"],
    "atlas copco": ["Atlas Copco"],
    "sullair": ["Sullair", "SULLAIR"],
    "bomag": ["Bomag", "BOMAG"],
    "hamm": ["Hamm", "HAMM"],
    "wirtgen": ["Wirtgen", "WIRTGEN"],
    "vogele": ["Vögele", "VOGELE", "Voegele"],
    "ammann": ["Ammann", "AMMANN"],
    "sumitomo": ["Sumitomo", "SUMITOMO"],
    "hidromek": ["Hidromek", "HMK"],
    "sany": ["SANY", "Sany", "三一"],
    "xcmg": ["XCMG", "徐工"],
    "zoomlion": ["Zoomlion", "ZOOMLION", "中联"],
    "liugong": ["LiuGong", "LIUGONG", "柳工"],
    "shantui": ["Shantui", "SHANTUI", "山推"],
    "lonking": ["Lonking", "LONKING", "龙工"],
    "dynapac": ["Dynapac", "DYNAPAC"],
    "tadano": ["Tadano", "TADANO"],
    "grove": ["Grove", "GROVE"],
    "merlo": ["Merlo", "MERLO"],
    "toyota": ["Toyota", "TOYOTA"],
    "linde": ["Linde", "LINDE"],
    "hyster": ["Hyster", "HYSTER"],
    "yale": ["Yale", "YALE"],
    "still": ["Still", "STILL"],
    "jungheinrich": ["Jungheinrich", "JUNGHEINRICH"],
    "clark": ["Clark", "CLARK"],
    "crown": ["Crown", "CROWN"],
    "tcm": ["TCM"]
}

# Ticari/satış siteleri - her aramadan hariç tut
EXCLUDED_DOMAINS = [
    "ebay.com", "ebay.de", "ebay.co.uk", "ebay.fr",
    "amazon.com", "amazon.de", "amazon.co.uk",
    "aliexpress.com", "alibaba.com",
    "autoepcservice.com", "epcatalogs.com",
    "heavymanuals.com", "themanualman.com",
    "sellfy.com", "payhip.com"
]

# Premium PDF platformları - ayrı tab için
PREMIUM_SITES = [
    # Global Platformlar
    "scribd.com",
    "issuu.com",
    "pdfcoffee.com",
    "calameo.com",
    "slideshare.net",
    "academia.edu",
    "researchgate.net",
    "pdfdrive.com",
    "pdfslide.net",
    "dokumen.tips",
    "fdocuments.net",
    "vdocuments.net",
    "cupdf.com",
    "vsepdf.com",
    "manualzz.com",
    # Çin Platformları
    "wenku.baidu.com",
    "docin.com",
    "book118.com",
    "doc88.com",
    "360doc.com",
    "max.book118.com",
    # Rusya Platformları
    "studfile.net",
    "topuch.ru",
    "studopedia.ru",
    # Japonya
    "slideshare.jp",
    # Kore
    "happycampus.com",
    # Almanya
    "yumpu.com",
]

VERIFIED_SOURCES = [
    {"domain": "kattrak.com", "pattern": "/wp-content/uploads/{filename}.pdf", "brands": ["Yanmar", "Hitachi"]},
    {"domain": "silverhorn.co.uk", "pattern": "/web/content/product.attachment/{id}/attachment/{filename}.pdf", "brands": ["Isuzu", "Yanmar", "AUSA"]},
    {"domain": "jacobsen.com", "pattern": "/manuals/{filename}.pdf", "brands": ["Kubota"]},
    {"domain": "ransomes.com", "pattern": "/manuals/{filename}.pdf", "brands": ["Kubota", "Ransomes"]},
    {"domain": "ayerbe.net", "pattern": "/wp-content/uploads/{year}/{month}/{filename}.pdf", "brands": ["Kubota", "Honda"]},
    {"domain": "pnevmomash.com", "pattern": "/assets/spare parts lists/{brand}/{category}/{filename}.pdf", "brands": ["Kubota", "Komatsu"]},
    {"domain": "canaldapeca.com.br", "pattern": "/catalogos/{folder}/{filename}.pdf", "brands": ["Cummins", "Perkins"]},
    {"domain": "s.siteapi.org", "pattern": "/{site_hash}/docs/{doc_hash}.pdf", "brands": ["Hitachi", "Cummins"]},
    {"domain": "hitachicm.com", "pattern": "/content/dam/hitachicm/{path}/{filename}.pdf", "brands": ["Hitachi"]},
    {"domain": "drivparts.com", "pattern": "/content/dam/marketing/{path}/{filename}.pdf", "brands": ["Komatsu"]},
    {"domain": "csapps.jlg.com", "pattern": "/CAGDocuments/MenuDocuments/{filename}.pdf", "brands": ["JLG"]},
    {"domain": "flextool.com.au", "pattern": "/media/{path}/{filename}.pdf", "brands": ["Kubota", "Yanmar", "Honda"]},
    {"domain": "multirentas.com", "pattern": "/wp-content/uploads/{year}/{month}/{filename}.pdf", "brands": ["Doosan", "Honda"]},
    {"domain": "jahancompressor.com", "pattern": "/upload/{folder}/{filename}.pdf", "brands": ["Sullair", "Atlas Copco", "CAT"]},
    {"domain": "bnhgenerators.com", "pattern": "/wp-content/uploads/{year}/{month}/{filename}.pdf", "brands": ["Doosan", "Cummins"]},
    {"domain": "optimaparts.nethouse.ru", "pattern": "/static/doc/{hash}.pdf", "brands": ["Liebherr", "CAT"]},
    {"domain": "dealers.doosanportablepower.com", "pattern": "/uploads/{folder}/{filename}.pdf", "brands": ["Doosan"]},
    {"domain": "junkkari.fi", "pattern": "/wp-content/uploads/{year}/{month}/{filename}.pdf", "brands": ["Junkkari"]}
]

